# Generated by Django 4.2.7 on 2023-11-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0002_alter_vender_avg_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='avg_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vender',
            name='on_time_delivery_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vender',
            name='quality_rating_avg',
            field=models.FloatField(null=True),
        ),
    ]
