# Generated by Django 4.2.7 on 2023-11-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vender', '0003_alter_vender_avg_response_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrdeers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=500, unique=True)),
                ('order_date', models.DateTimeField(null=True)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('items', models.JSONField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100)),
                ('quality_rating', models.FloatField(null=True)),
                ('issue_date', models.DateTimeField(auto_now=True)),
                ('acknowledgment_date', models.DateTimeField(null=True)),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vender_order', to='vender.vender')),
            ],
        ),
    ]
